=== obsgolem/LOGOSTools/schema.json
{
    "$schema": "https://json-schema.org/draft-07/schema",
    "$id": "https://raw.githubusercontent.com/obsgolem/LOGOSTools/main/schema.json",
    "title": "Chapter Vocabulary",
    "description": "The vocab list for a single chapter of ΛΟΓΟΣ",
    "type": "object",
    "properties": {
        "chapter_name": {
            "description": "The chapter's name",
            "type": "string"
        },
        "word_list_page_number": {
            "description": "The page number in the book for this list",
            "type": "number"
        },
        "exercise_page_range": {
            "description": "The page range for the exercises for this chapter",
            "type": "array",
            "minItems": 2,
            "maxItems": 2,
            "items": {
                "type": "number"
            }
        },
        "sections": {
            "type": "array",
            "items": {
                "description": "The collection of words under a section header in the book",
                "type": "object",
                "properties": {
                    "section": {
                        "description": "The name of the section in the book",
                        "type": "string"
                    },
                    "words": {
                        "type": "array",
                        "items": {
                            "description": "The data for a single vocab entry",
                            "type": "object",
                            "properties": {
                                "book_entry": {
                                    "description": "The raw text in the book",
                                    "type": "string"
                                },
                                "first_occurrence": {
                                    "description": "The line and word number (1 indexed) of the first occurrence of the word in the book.",
                                    "type": "array",
                                    "minItems": 1,
                                    "maxItems": 2,
                                    "items": {
                                        "type": "number"
                                    }
                                },
                                "macronized": {
                                    "description": "The entry with any ambiguous long vowels macronized.",
                                    "type": "string"
                                },
                                "gloss": {
                                    "description": "A short definition in english for the word.",
                                    "type": "string"
                                }
                            },
                            "additionalProperties": false,
                            "required": [
                                "book_entry"
                            ]
                        }
                    }
                },
                "additionalProperties": false,
                "required": [
                    "section",
                    "words"
                ]
            }
        }
    }
}

=== obsgolem/LOGOSTools/json/Ch 25.json
{
  "chapter_name": "ΓΛΩΣΣΑ ΚΑΙ ΔΙΑΛΕΚΤΟΙ",
  "word_list_page_number": 274,
  "exercise_page_range": [
    269,
    273
  ],
  "sections": [
    {
      "section": "Ὀνόματα",
      "words": [
        {
          "book_entry": "ἀπόγονος, ὁ",
          "first_occurrence": [
            52,
            5
          ]
        },
        {
          "book_entry": "ἀρχηγέτης, ὁ",
          "first_occurrence": [
            60,
            1
          ]
        },
        {
          "book_entry": "γενάρχης, ὁ",
          "first_occurrence": [
            68,
            2
          ]
        },
        {
          "book_entry": "διάλεκτος, ἡ",
          "first_occurrence": [
            100,
            1
          ]
        },
        {
          "book_entry": "ἡγεμονία, ἡ",
          "first_occurrence": [
            89,
            6
          ]
        },
        {
          "book_entry": "ἱστοριογράφος, ὁ",
          "first_occurrence": [
            109,
            2
          ]
        },
        {
          "book_entry": "κάτοικος, ὁ",
          "first_occurrence": [
            46,
            7
          ]
        },
        {
          "book_entry": "παροιμία, ἡ"
        },
        {
          "book_entry": "ῥήτωρ, ὁ",
          "first_occurrence": [
            88,
            2
          ]
        },
        {
          "book_entry": "τόπος, ὁ",
          "first_occurrence": [
            21,
            3
          ]
        },
        {
          "book_entry": "φυλή, ἡ",
          "first_occurrence": [
            59,
            6
          ]
        },
        {
          "book_entry": "χώρος, ὁ",
          "first_occurrence": [
            63,
            6
          ]
        }
      ]
    },
    {
      "section": "Κύρια ὀνόματα",
      "words": [
        {
          "book_entry": "Αἴολος, ὁ"
        },
        {
          "book_entry": "Ἀλκαῖος, ὁ"
        },
        {
          "book_entry": "Ἀλκμάν, ὁ"
        },
        {
          "book_entry": "Ἀχαία, ἡ"
        },
        {
          "book_entry": "Γραικός, ὁ"
        },
        {
          "book_entry": "Δωρίς, ἡ"
        },
        {
          "book_entry": "Δῶρος, ὁ"
        },
        {
          "book_entry": "Ἕλλην, ὁ"
        },
        {
          "book_entry": "Ζήνων, ὁ"
        },
        {
          "book_entry": "Θήρα, ἡ"
        },
        {
          "book_entry": "Θυία, ἡ"
        },
        {
          "book_entry": "Κίτιον, τό"
        },
        {
          "book_entry": "Κρέουσα, ἡ"
        },
        {
          "book_entry": "Ξούθος, ὁ"
        },
        {
          "book_entry": "Πίνδαρος, ὁ"
        },
        {
          "book_entry": "Φθία. ἡ"
        }
      ]
    },
    {
      "section": "Ἐπίθετα",
      "words": [
        {
          "book_entry": "Αἰολεύς, Αἰολίς",
          "first_occurrence": [
            39,
            2
          ]
        },
        {
          "book_entry": "αἰολικός. -ή, -όν",
          "first_occurrence": [
            99,
            6
          ]
        },
        {
          "book_entry": "Ἁλικαρνασσεύς, -ίς",
          "first_occurrence": [
            109,
            1
          ]
        },
        {
          "book_entry": "ἄριστος, -η, -ον",
          "first_occurrence": [
            87,
            7
          ]
        },
        {
          "book_entry": "ἀρχαῖος, -α, -ον",
          "first_occurrence": [
            38,
            2
          ]
        },
        {
          "book_entry": "Ἀχαιός, -ά",
          "first_occurrence": [
            39,
            2
          ]
        },
        {
          "book_entry": "βάρβαρος, -ον",
          "first_occurrence": [
            18,
            2
          ]
        },
        {
          "book_entry": "Βοιώτιος, -α",
          "first_occurrence": [
            48,
            4
          ]
        },
        {
          "book_entry": "Γαλάτης, Γαλάτισσα",
          "first_occurrence": [
            29,
            5
          ]
        },
        {
          "book_entry": "Γραικός, -ή",
          "first_occurrence": [
            51,
            5
          ]
        },
        {
          "book_entry": "Δωριεύς, Δωρίς",
          "first_occurrence": [
            39,
            3
          ]
        },
        {
          "book_entry": "ἐθνικός, -ή, -ον"
        },
        {
          "book_entry": "Ἑλλαδικός, -ή, -όν",
          "first_occurrence": [
            63,
            5
          ]
        },
        {
          "book_entry": "Ἐφέσιος, -α",
          "first_occurrence": [
            50,
            1
          ]
        },
        {
          "book_entry": "Θεσσαλός, -ίς",
          "first_occurrence": [
            48,
            2
          ]
        },
        {
          "book_entry": "Θηβαῖος, -α",
          "first_occurrence": [
            105,
            7
          ]
        },
        {
          "book_entry": "Ἴβηρ, Ἰβηρίς",
          "first_occurrence": [
            32,
            7
          ]
        },
        {
          "book_entry": "Ἴων, Ἰωνίς"
        },
        {
          "book_entry": "Κιτιεύς, Κιτίς",
          "first_occurrence": [
            123,
            6
          ]
        },
        {
          "book_entry": "Κορίνθιος, -α",
          "first_occurrence": [
            45,
            1
          ]
        },
        {
          "book_entry": "Κρής, Κρῆσσα"
        },
        {
          "book_entry": "Κύπριος, -α",
          "first_occurrence": [
            123,
            1
          ]
        },
        {
          "book_entry": "Λέσβιος, Λεσβίς",
          "first_occurrence": [
            114,
            6
          ]
        },
        {
          "book_entry": "Μῆδος, Μηδίς"
        },
        {
          "book_entry": "Μιλήσιος, -α"
        },
        {
          "book_entry": "Πάριος, -α"
        },
        {
          "book_entry": "Πέρσης, Περσίς"
        },
        {
          "book_entry": "Ῥόδιος, -α"
        },
        {
          "book_entry": "Ῥωμαῖος, -α"
        },
        {
          "book_entry": "Σάμιος. -α"
        },
        {
          "book_entry": "Σμυρναῖος, -α"
        },
        {
          "book_entry": "Σύριος, -α"
        },
        {
          "book_entry": "τοπικός, -ή, -όν",
          "first_occurrence": [
            99,
            2
          ]
        }
      ]
    },
    {
      "section": "Ῥήματα",
      "words": [
        {
          "book_entry": "αἰολίζω",
          "first_occurrence": [
            112,
            4
          ]
        },
        {
          "book_entry": "ἀποδοκιμάζω"
        },
        {
          "book_entry": "ἀττικίζω",
          "first_occurrence": [
            117,
            3
          ]
        },
        {
          "book_entry": "βαρβαρίζω",
          "first_occurrence": [
            26,
            7
          ]
        },
        {
          "book_entry": "βασιλεύω",
          "first_occurrence": [
            79,
            4
          ]
        },
        {
          "book_entry": "γεννάω",
          "first_occurrence": [
            75,
            4
          ]
        },
        {
          "book_entry": "διαφέρω"
        },
        {
          "book_entry": "δωρίζω",
          "first_occurrence": [
            101,
            4
          ]
        },
        {
          "book_entry": "ἑλληνίζω",
          "first_occurrence": [
            9,
            5
          ]
        },
        {
          "book_entry": "ἐπίσταμαι",
          "first_occurrence": [
            2,
            5
          ]
        },
        {
          "book_entry": "ἰωνίζω",
          "first_occurrence": [
            107,
            4
          ]
        },
        {
          "book_entry": "λαλέω",
          "first_occurrence": [
            2,
            3
          ]
        },
        {
          "book_entry": "μερίζω",
          "first_occurrence": [
            73,
            5
          ]
        },
        {
          "book_entry": "ὀνομάζω, -ομαι",
          "first_occurrence": [
            63,
            1
          ]
        },
        {
          "book_entry": "προσαγορεύω",
          "first_occurrence": [
            95,
            6
          ]
        }
      ]
    },
    {
      "section": "Προθέσεις",
      "words": [
        {
          "book_entry": "περί (+ αἰτ.)"
        }
      ]
    },
    {
      "section": "Ἀντωνυμίαι",
      "words": [
        {
          "book_entry": "ὅσοι, ὅσαι, ὅσα",
          "first_occurrence": [
            17,
            3
          ]
        }
      ]
    },
    {
      "section": "Ἐπιρήματα",
      "words": [
        {
          "book_entry": "ἑλληνιστί",
          "first_occurrence": [
            6,
            6
          ]
        },
        {
          "book_entry": "πέραν",
          "first_occurrence": [
            77,
            4
          ]
        },
        {
          "book_entry": "πρότερον",
          "first_occurrence": [
            71,
            8
          ]
        }
      ]
    },
    {
      "section": "Φράσεις",
      "words": [
        {
          "book_entry": "Χαλεπὰ τὰ καλά",
          "first_occurrence": [
            36,
            1
          ]
        }
      ]
    }
  ]
}

=== obsgolem/LOGOSTools/json/Ch 18.json
{
  "chapter_name": "ΟΙ ΠΑΙΔΕΣ",
  "word_list_page_number": 192,
  "exercise_page_range": [
    188,
    191
  ],
  "sections": [
    {
      "section": "Ῥήματα",
      "words": [
        {
          "book_entry": "ἄγω"
        },
        {
          "book_entry": "αἱρέω"
        },
        {
          "book_entry": "ἀλγέω"
        },
        {
          "book_entry": "ἀποχωρέω"
        },
        {
          "book_entry": "βοηθέω"
        },
        {
          "book_entry": "βούλομαι"
        },
        {
          "book_entry": "γεωργέω"
        },
        {
          "book_entry": "διδάσκω"
        },
        {
          "book_entry": "δύναμαι"
        },
        {
          "book_entry": "ἐργάζομαι"
        },
        {
          "book_entry": "ἥκω"
        },
        {
          "book_entry": "ἰλιγγιάω"
        },
        {
          "book_entry": "κάθημαι"
        },
        {
          "book_entry": "κατασκευάζω"
        },
        {
          "book_entry": "μισέω"
        },
        {
          "book_entry": "οἶδα"
        },
        {
          "book_entry": "πίπτω"
        },
        {
          "book_entry": "πταῖω"
        },
        {
          "book_entry": "φημί"
        }
      ]
    },
    {
      "section": "Ἐκφράσεις",
      "words": [
        {
          "book_entry": "οὐ γὰρ οὖν!"
        },
        {
          "book_entry": "τί ἔστιν;"
        }
      ]
    },
    {
      "section": "Ὀνόματα",
      "words": [
        {
          "book_entry": "ἄγαλμα, τό"
        },
        {
          "book_entry": "ἀγγεῖον, τό"
        },
        {
          "book_entry": "ἀστρονόμος, ὁ"
        },
        {
          "book_entry": "βοήθεια, ἡ"
        },
        {
          "book_entry": "γλύπτης, ὁ"
        },
        {
          "book_entry": "διδασκαλεῖον, τό"
        },
        {
          "book_entry": "διδάσκαλος, ὁ"
        },
        {
          "book_entry": "κεραμεύς, ὁ"
        },
        {
          "book_entry": "λόγος, ὁ"
        },
        {
          "book_entry": "_μετοχή, ἡ_"
        },
        {
          "book_entry": "ναύτης, ὁ"
        },
        {
          "book_entry": "ὄχθη, ἡ"
        },
        {
          "book_entry": "πλοῖον, τό"
        },
        {
          "book_entry": "προθυμία, ἡ"
        },
        {
          "book_entry": "στρατηγός, ὁ"
        },
        {
          "book_entry": "τάφος, ὁ"
        },
        {
          "book_entry": "φόβος, ὁ"
        }
      ]
    },
    {
      "section": "Ἐπιφωνήματα",
      "words": [
        {
          "book_entry": "αἰαῖ!"
        },
        {
          "book_entry": "φεῦ!"
        }
      ]
    },
    {
      "section": "Ἐπιρρήματα",
      "words": [
        {
          "book_entry": "δεῦρο"
        }
      ]
    },
    {
      "section": "Κύρια ὀνόματα",
      "words": [
        {
          "book_entry": "Ἀγαμέμνων, ὁ"
        },
        {
          "book_entry": "Ἀκρόπολις, ἡ"
        },
        {
          "book_entry": "Ἀναξίμανδρος, ὁ"
        },
        {
          "book_entry": "Ἀρχέλαος, ὁ"
        },
        {
          "book_entry": "Κεραμεικός, ὁ"
        },
        {
          "book_entry": "Λακεδαίμων, ἡ"
        },
        {
          "book_entry": "Λεωνίδας, ὁ"
        },
        {
          "book_entry": "Λύσιππος, ὁ"
        },
        {
          "book_entry": "Μενέλαος, ὁ"
        },
        {
          "book_entry": "Πλάτων, ὁ"
        },
        {
          "book_entry": "Πραξιτέλης, ὁ"
        }
      ]
    },
    {
      "section": "Ἐπίθετα",
      "words": [
        {
          "book_entry": "ἀκίνητος, -ον"
        },
        {
          "book_entry": "Λακεδαιμόνιος, -α"
        },
        {
          "book_entry": "Μακεδών, Μακεδόνισσα"
        },
        {
          "book_entry": "ξένος, -η, -ον"
        },
        {
          "book_entry": "ὅλος, -η, -ον"
        }
      ]
    },
    {
      "section": "Προθέσεις",
      "words": [
        {
          "book_entry": "ἐκτός"
        },
        {
          "book_entry": "ἐντός"
        },
        {
          "book_entry": "πρός + δοτ."
        }
      ]
    }
  ]
}

=== obsgolem/LOGOSTools/json/Ch 32.json
{
  "chapter_name": "ΠΕΡI ΕΙΡΗΝΗΣ",
  "word_list_page_number": 364,
  "exercise_page_range": [
    358,
    363
  ],
  "sections": [
    {
      "section": "Ῥήματα",
      "words": [
        {
          "book_entry": "ἀναμένω"
        },
        {
          "book_entry": "ἀπαγγέλλω"
        },
        {
          "book_entry": "ἀπογράφω, -ομαι"
        },
        {
          "book_entry": "δέω"
        },
        {
          "book_entry": "διαπράσσω, -ομαι"
        },
        {
          "book_entry": "ἐγκαθίστημι"
        },
        {
          "book_entry": "ἐπιτελέω"
        },
        {
          "book_entry": "ἥδομαι"
        },
        {
          "book_entry": "καταπολεμέω, -ομαι"
        },
        {
          "book_entry": "λακωνίζω"
        },
        {
          "book_entry": "μεταγράφω"
        },
        {
          "book_entry": "μεταπέμπω, -ομαι"
        },
        {
          "book_entry": "οἶμαι"
        },
        {
          "book_entry": "ὄμνυμι"
        },
        {
          "book_entry": "ὁμογνωμονέω"
        },
        {
          "book_entry": "παρακαλέω"
        },
        {
          "book_entry": "παρέρχομαι"
        },
        {
          "book_entry": "προηγορέω"
        },
        {
          "book_entry": "προσκρούω"
        },
        {
          "book_entry": "ὑποτάσσω, -ομαι"
        },
        {
          "book_entry": "φαίνομαι"
        },
        {
          "book_entry": "φιλονικέω"
        },
        {
          "book_entry": "φρονέω"
        }
      ]
    },
    {
      "section": "Ὀνόματα",
      "words": [
        {
          "book_entry": "ἀμάρτημα, τό"
        },
        {
          "book_entry": "ἀρμοστής, ὁ"
        },
        {
          "book_entry": "αὐτονομία, ἡ"
        },
        {
          "book_entry": "γνώμη, ἡ"
        },
        {
          "book_entry": "διοικητής, ὁ"
        },
        {
          "book_entry": "δυσκολία, ἡ"
        },
        {
          "book_entry": "κατάλυσις, ἡ"
        },
        {
          "book_entry": "πράξις, ἡ"
        },
        {
          "book_entry": "πρεσβεία, ἡ"
        },
        {
          "book_entry": "σιωπή, ἡ"
        },
        {
          "book_entry": "ταραχή, ἡ"
        },
        {
          "book_entry": "φρουρά, ἡ"
        }
      ]
    },
    {
      "section": "Ἀντωνυμίαι",
      "words": [
        {
          "book_entry": "ὑμεῖς"
        }
      ]
    },
    {
      "section": "Μόρια",
      "words": [
        {
          "book_entry": "ἄρα"
        }
      ]
    },
    {
      "section": "Σύνδεσμοι",
      "words": [
        {
          "book_entry": "ἐάν (εἰ - ἄν)"
        }
      ]
    },
    {
      "section": "Προθέσεις",
      "words": [
        {
          "book_entry": "ἀντί"
        }
      ]
    },
    {
      "section": "Ἐπίθετα",
      "words": [
        {
          "book_entry": "ἄδικος, -ον"
        },
        {
          "book_entry": "ἀναμάρτητος, -ον"
        },
        {
          "book_entry": "ἀνάξιος, -ον"
        },
        {
          "book_entry": "ἀντίτυπος, -ον"
        },
        {
          "book_entry": "ἄπρακτος, -ον"
        },
        {
          "book_entry": "αὐτόνομος, -ον"
        },
        {
          "book_entry": "εὔπορος, -ον"
        },
        {
          "book_entry": "σχολαῖος, -α, -ον"
        },
        {
          "book_entry": "σώφρων, -ον"
        }
      ]
    },
    {
      "section": "Ἐπιρρήματα",
      "words": [
        {
          "book_entry": "ἀθύμως"
        },
        {
          "book_entry": "ἄλλως"
        },
        {
          "book_entry": "ἀφρόνως"
        },
        {
          "book_entry": "δήπου"
        },
        {
          "book_entry": "δίς"
        },
        {
          "book_entry": "ἐμποδών"
        },
        {
          "book_entry": "πολεμικῶς"
        },
        {
          "book_entry": "πρόσθεν"
        },
        {
          "book_entry": "πως"
        },
        {
          "book_entry": "ὑμέτερος, -α, -ον"
        },
        {
          "book_entry": "σωφρόνως"
        }
      ]
    }
  ]
}

=== obsgolem/LOGOSTools/json/Ch 12.json
{
  "chapter_name": "Η ΥΠΑΤΙΑ",
  "word_list_page_number": 124,
  "exercise_page_range": [
    120,
    123
  ],
  "sections": [
    {
      "section": "Ὀνόματα",
      "words": [
        {
          "book_entry": "ἀγορά, ἡ"
        },
        {
          "book_entry": "ἀθλητής, ὁ"
        },
        {
          "book_entry": "ἄνθος, τό"
        },
        {
          "book_entry": "ἄροτρον, τό"
        },
        {
          "book_entry": "γέρων, ὁ"
        },
        {
          "book_entry": "γραῦς, ἡ"
        },
        {
          "book_entry": "δίσκος, ὁ"
        },
        {
          "book_entry": "ἔτος, τό"
        },
        {
          "book_entry": "ἱμάτιον, τό"
        },
        {
          "book_entry": "ἱματιοπώλης, ὁ"
        },
        {
          "book_entry": "κιθαριστής, ὁ"
        },
        {
          "book_entry": "κλῆρος, ὁ"
        },
        {
          "book_entry": "κρήνη, ἡ"
        },
        {
          "book_entry": "οἰκονόμος, ὁ / ὴ"
        },
        {
          "book_entry": "ποίημα, τό"
        },
        {
          "book_entry": "πόνος, ὁ"
        },
        {
          "book_entry": "τροφός, ἡ"
        }
      ]
    },
    {
      "section": "Ἀντωνυμίαι",
      "words": [
        {
          "book_entry": "οὗτος, αὕτη, τοῦτο"
        },
        {
          "book_entry": "ποῖος; ποία; ποῖον;"
        }
      ]
    },
    {
      "section": "Ἐπίθετα",
      "words": [
        {
          "book_entry": "ἀγαθός, -ή, -όν"
        },
        {
          "book_entry": "Ἀθηναῖος, -α, -ον"
        },
        {
          "book_entry": "ἀνδρεῖος, -α, -ον"
        },
        {
          "book_entry": "ἀνήσυχος. -ον"
        },
        {
          "book_entry": "ἄσχημος. -ον"
        },
        {
          "book_entry": "δεινός, -ή, -όν"
        },
        {
          "book_entry": "δύσκολος, -ον"
        },
        {
          "book_entry": "ἐπιδέξιος, -ον"
        },
        {
          "book_entry": "ἤσυχος, -ον"
        },
        {
          "book_entry": "ἰσχυρός, -ά, -όν"
        },
        {
          "book_entry": "_κτητικός, -ἤ, -ον_"
        },
        {
          "book_entry": "πλούσιος, -α, -ον"
        },
        {
          "book_entry": "ῥᾴθυμος, -ον"
        },
        {
          "book_entry": "φιλάνθρωπος, -ον"
        },
        {
          "book_entry": "φιλόπονος, -ον"
        },
        {
          "book_entry": "χῆρος, -α, -ον"
        }
      ]
    },
    {
      "section": "Ἐπιρρήματα",
      "words": [
        {
          "book_entry": "ἀεί"
        },
        {
          "book_entry": "ἄριστα"
        },
        {
          "book_entry": "μάλα"
        },
        {
          "book_entry": "οὔπω"
        }
      ]
    },
    {
      "section": "Ῥήματα",
      "words": [
        {
          "book_entry": "ᾄδω"
        },
        {
          "book_entry": "ἀροτρεύω"
        },
        {
          "book_entry": "διοικέω"
        },
        {
          "book_entry": "ἐσθίω"
        },
        {
          "book_entry": "θηλάζω"
        },
        {
          "book_entry": "κιθαρίζω"
        },
        {
          "book_entry": "κλαίω"
        },
        {
          "book_entry": "πλύνω"
        },
        {
          "book_entry": "πονέω"
        },
        {
          "book_entry": "πωλέω"
        },
        {
          "book_entry": "συλλέγω"
        }
      ]
    },
    {
      "section": "Ἀριθμοί",
      "words": [
        {
          "book_entry": "ἑβδομήκοντα"
        },
        {
          "book_entry": "εἴκοσι"
        },
        {
          "book_entry": "ἑξήκοντα"
        },
        {
          "book_entry": "πεντεκαίδεκα"
        },
        {
          "book_entry": "τεσσαράκοντα"
        },
        {
          "book_entry": "τριάκοντα"
        }
      ]
    },
    {
      "section": "Προθέσεις",
      "words": [
        {
          "book_entry": "κατά (καθ ̓ ἡμέραν)"
        }
      ]
    }
  ]
}
