=== obsgolem/LOGOSTools/schema.json
{
    "$schema": "https://json-schema.org/draft-07/schema",
    "$id": "https://raw.githubusercontent.com/obsgolem/LOGOSTools/main/schema.json",
    "title": "Chapter Vocabulary",
    "description": "The vocab list for a single chapter of ΛΟΓΟΣ",
    "type": "object",
    "properties": {
        "chapter_name": {
            "description": "The chapter's name",
            "type": "string"
        },
        "word_list_page_number": {
            "description": "The page number in the book for this list",
            "type": "number"
        },
        "exercise_page_range": {
            "description": "The page range for the exercises for this chapter",
            "type": "array",
            "minItems": 2,
            "maxItems": 2,
            "items": {
                "type": "number"
            }
        },
        "sections": {
            "type": "array",
            "items": {
                "description": "The collection of words under a section header in the book",
                "type": "object",
                "properties": {
                    "section": {
                        "description": "The name of the section in the book",
                        "type": "string"
                    },
                    "words": {
                        "type": "array",
                        "items": {
                            "description": "The data for a single vocab entry",
                            "type": "object",
                            "properties": {
                                "book_entry": {
                                    "description": "The raw text in the book",
                                    "type": "string"
                                },
                                "first_occurrence": {
                                    "description": "The line and word number (1 indexed) of the first occurrence of the word in the book.",
                                    "type": "array",
                                    "minItems": 1,
                                    "maxItems": 2,
                                    "items": {
                                        "type": "number"
                                    }
                                },
                                "macronized": {
                                    "description": "The entry with any ambiguous long vowels macronized.",
                                    "type": "string"
                                },
                                "gloss": {
                                    "description": "A short definition in english for the word.",
                                    "type": "string"
                                }
                            },
                            "additionalProperties": false,
                            "required": [
                                "book_entry"
                            ]
                        }
                    }
                },
                "additionalProperties": false,
                "required": [
                    "section",
                    "words"
                ]
            }
        }
    }
}

=== obsgolem/LOGOSTools/json/Ch 8.json
{
  "chapter_name": "Η ΕΥΡΩΠΗ",
  "word_list_page_number": 84,
  "exercise_page_range": [
    81,
    83
  ],
  "sections": [
    {
      "section": "Κύρια ὀνόματα",
      "words": [
        {
          "book_entry": "Αἴγυπτος, ἡ",
          "gloss": "Egypt (f.); king Aegyptus (m.)"
        },
        {
          "book_entry": "Ἀκράγας, ὁ",
          "gloss": "Acragas"
        },
        {
          "book_entry": "Ἀλεξάνδρεια, ἡ",
          "gloss": "Alexandria"
        },
        {
          "book_entry": "Ἀντιόχεια, ἡ",
          "gloss": "Antiochia"
        },
        {
          "book_entry": "Ἀραβία, ἡ",
          "gloss": "Arabia"
        },
        {
          "book_entry": "Γαλατία, ἡ",
          "gloss": "Galatia"
        },
        {
          "book_entry": "Ἔβυσος. ἡ"
        },
        {
          "book_entry": "Ἔλλάς, ἡ"
        },
        {
          "book_entry": "Ἔμπόριον, τό"
        },
        {
          "book_entry": "Εὔξεινος Πόντος, ὁ"
        },
        {
          "book_entry": "Εὐφράτης, ὁ",
          "gloss": "the river Euphrates"
        },
        {
          "book_entry": "Ἡράκλειον, τό",
          "gloss": "sanctuary of Heracles"
        },
        {
          "book_entry": "Θούριοι, οἱ"
        },
        {
          "book_entry": "Θύμβρις, ὁ",
          "gloss": "the Tiber"
        },
        {
          "book_entry": "Ἰβηρία. ἡ"
        },
        {
          "book_entry": "Ἰνδία, ἡ"
        },
        {
          "book_entry": "Ἴστρος, ὁ",
          "gloss": "Ister, Danube"
        },
        {
          "book_entry": "Ἰταλία. ἡ"
        },
        {
          "book_entry": "Κρήτη, ἡ",
          "gloss": "Crete"
        },
        {
          "book_entry": "Κύπρος, ἡ",
          "gloss": "Cyprus"
        },
        {
          "book_entry": "Κυρήνη, ἡ",
          "gloss": "Cyrene"
        },
        {
          "book_entry": "Λεοντίνοι, οἱ"
        },
        {
          "book_entry": "Λυδία, ἡ",
          "gloss": "Lydia"
        },
        {
          "book_entry": "Μασσαλία, ἡ",
          "gloss": "Massalia, Marseilles"
        },
        {
          "book_entry": "Μελίτα, ἡ"
        },
        {
          "book_entry": "Μεσσήνη, ἡ",
          "gloss": "Messene"
        },
        {
          "book_entry": "Μίνιος, ὁ"
        },
        {
          "book_entry": "Νάξος, ἡ",
          "gloss": "Naxos (f. island, m. mythical founder)"
        },
        {
          "book_entry": "Νεάπολις, ἡ",
          "gloss": "new city"
        },
        {
          "book_entry": "Νεῖλος, ὁ",
          "gloss": "the Nile"
        },
        {
          "book_entry": "Περσίς, ἡ",
          "gloss": "Persian"
        },
        {
          "book_entry": "Πιτυούσσαι, αἱ"
        },
        {
          "book_entry": "Πομπηία, ἡ"
        },
        {
          "book_entry": "Ῥῆνος, ὁ"
        },
        {
          "book_entry": "Ῥόδη, ἡ"
        },
        {
          "book_entry": "Ῥόδος, ἡ",
          "gloss": "Rhodes"
        },
        {
          "book_entry": "Ῥώμη, ἡ",
          "gloss": "Roma, Rome"
        },
        {
          "book_entry": "Σικελία, ἡ",
          "gloss": "Sicily"
        },
        {
          "book_entry": "Συράκουσαι, αἱ",
          "gloss": "Syracuse"
        },
        {
          "book_entry": "Συρία, ἡ",
          "gloss": "Syria"
        },
        {
          "book_entry": "Τίγρις, ὁ"
        },
        {
          "book_entry": "Τύρος, ἡ",
          "gloss": "Tyre"
        },
        {
          "book_entry": "Χίος, ἡ",
          "gloss": "Chios (island)"
        }
      ]
    },
    {
      "section": "Ὀνόματα",
      "words": [
        {
          "book_entry": "ἀποικία, ἡ",
          "first_occurrence": [
            69,
            4
          ],
          "gloss": "a settlement far from home, a colony settlement"
        },
        {
          "book_entry": "χώρα, ἡ",
          "first_occurrence": [
            2,
            5
          ],
          "gloss": "land, country"
        }
      ]
    }
  ]
}

=== obsgolem/LOGOSTools/json/Ch 10.json
{
  "chapter_name": "Η ΟΙΚΙΑ",
  "word_list_page_number": 102,
  "exercise_page_range": [
    98,
    101
  ],
  "sections": [
    {
      "section": "Ῥήματα",
      "words": [
        {
          "book_entry": "ᾄδω"
        },
        {
          "book_entry": "ἀναγιγνώσκω"
        },
        {
          "book_entry": "ἀναπαύομαι"
        },
        {
          "book_entry": "ἄπειμι"
        },
        {
          "book_entry": "διατρίβω"
        },
        {
          "book_entry": "δύει"
        },
        {
          "book_entry": "εὑρίσκω"
        },
        {
          "book_entry": "ἔχω"
        },
        {
          "book_entry": "ζητέω"
        },
        {
          "book_entry": "θεραπεύω"
        },
        {
          "book_entry": "καθεύδω"
        },
        {
          "book_entry": "καλέω"
        },
        {
          "book_entry": "κτενίζω"
        },
        {
          "book_entry": "λαμβάνω"
        },
        {
          "book_entry": "λείπω"
        },
        {
          "book_entry": "λούω, -ομαι"
        },
        {
          "book_entry": "μαγειρεύω"
        },
        {
          "book_entry": "ὁράω"
        },
        {
          "book_entry": "παρασκευάζω"
        },
        {
          "book_entry": "πάρειμι"
        },
        {
          "book_entry": "ῥάπτω"
        },
        {
          "book_entry": "τρέφω"
        },
        {
          "book_entry": "φιλέω"
        }
      ]
    },
    {
      "section": "Προθέσεις",
      "words": [
        {
          "book_entry": "κατά (κατ ̓ οἰκον)"
        }
      ]
    },
    {
      "section": "Ὀνόματα",
      "words": [
        {
          "book_entry": "ἀνδρωνῖτις, ἡ"
        },
        {
          "book_entry": "ἀποθήκη, ἡ"
        },
        {
          "book_entry": "αὐλή, ἡ"
        },
        {
          "book_entry": "αὔλιον, τό"
        },
        {
          "book_entry": "βιβλιοθήκη, ἡ"
        },
        {
          "book_entry": "βιβλίον, τό"
        },
        {
          "book_entry": "βωμός, ὁ"
        },
        {
          "book_entry": "γυναικωνῖτις, ἡ"
        },
        {
          "book_entry": "δεῖπνον, τό"
        },
        {
          "book_entry": "δωμάτιον, τό"
        },
        {
          "book_entry": "ἐπιστολή, ἡ"
        },
        {
          "book_entry": "ἔργον, τό"
        },
        {
          "book_entry": "ἑσπέρα, ἡ"
        },
        {
          "book_entry": "ἡμέρα, ῆ"
        },
        {
          "book_entry": "θάλαμος, ὁ"
        },
        {
          "book_entry": "θρόνος, ὁ"
        },
        {
          "book_entry": "θύρα, ἡ"
        },
        {
          "book_entry": "θυρίς, ἡ"
        },
        {
          "book_entry": "καθέδρα, ἡ"
        },
        {
          "book_entry": "κάλαμος, ὁ"
        },
        {
          "book_entry": "κῆπος, ὁ"
        },
        {
          "book_entry": "κιβώτιον, τό"
        },
        {
          "book_entry": "κιθάρα, ἡ"
        },
        {
          "book_entry": "κλίμαξ, ἡ"
        },
        {
          "book_entry": "κλίνη, ἡ"
        },
        {
          "book_entry": "κόμη, ἡ"
        },
        {
          "book_entry": "λουτρόν, τό"
        },
        {
          "book_entry": "μαγειρεῖον, τό"
        },
        {
          "book_entry": "μῆλον, τό"
        },
        {
          "book_entry": "νύξ, ἡ"
        },
        {
          "book_entry": "ξύλον, τό"
        },
        {
          "book_entry": "ὄνειρον, τό"
        },
        {
          "book_entry": "πάπυρος, ὁ"
        },
        {
          "book_entry": "πέπλος, ὁ"
        },
        {
          "book_entry": "περιστύλιον, τό"
        },
        {
          "book_entry": "στῦλος, ὁ"
        },
        {
          "book_entry": "συμπόσιον, τό"
        },
        {
          "book_entry": "τράπεζα, ἡ"
        },
        {
          "book_entry": "τροφή, ἡ"
        },
        {
          "book_entry": "ὕπνος, ὁ"
        }
      ]
    },
    {
      "section": "Ἐπίθετα",
      "words": [
        {
          "book_entry": "αἰτιατικός, -ή, -όν"
        },
        {
          "book_entry": "διπλοῦς, -ῆ, -οῦν"
        },
        {
          "book_entry": "_κλητικός, -ή, -όν_"
        },
        {
          "book_entry": "ξύλινος, -η, -ον"
        },
        {
          "book_entry": "περίστυλος, -ον"
        }
      ]
    },
    {
      "section": "Ἐπιρρήματα",
      "words": [
        {
          "book_entry": "ἅμα"
        },
        {
          "book_entry": "ἤδη"
        },
        {
          "book_entry": "καλῶς"
        },
        {
          "book_entry": "τέλος"
        }
      ]
    },
    {
      "section": "Ἐπιρωνήματα",
      "words": [
        {
          "book_entry": "ὦ!"
        }
      ]
    }
  ]
}

=== obsgolem/LOGOSTools/json/Ch 30.json
{
  "chapter_name": "ΤΑ ΜΗΔΙΚΑ",
  "word_list_page_number": 339,
  "exercise_page_range": [
    335,
    338
  ],
  "sections": [
    {
      "section": "Ῥήματα",
      "words": [
        {
          "book_entry": "ἀγγέλλω"
        },
        {
          "book_entry": "ἀναμιμνήσκω"
        },
        {
          "book_entry": "ἀντέχω, -ομαι"
        },
        {
          "book_entry": "ἀπεικονίζω"
        },
        {
          "book_entry": "ἄπειμι (< εἶμι)"
        },
        {
          "book_entry": "ἀποστέλλω"
        },
        {
          "book_entry": "ἀφίστημι"
        },
        {
          "book_entry": "δηλόω"
        },
        {
          "book_entry": "διαπεραιόω, -ομαι"
        },
        {
          "book_entry": "δουλόω"
        },
        {
          "book_entry": "δράω"
        },
        {
          "book_entry": "ἐκλείπω"
        },
        {
          "book_entry": "ἐπαινέω"
        },
        {
          "book_entry": "ἐρύω"
        },
        {
          "book_entry": "ἐφίσταμαι"
        },
        {
          "book_entry": "ἡττάομαι"
        },
        {
          "book_entry": "θρηνέω"
        },
        {
          "book_entry": "καταλαμβάνω"
        },
        {
          "book_entry": "καταφρονέω"
        },
        {
          "book_entry": "κωλύω"
        },
        {
          "book_entry": "μάχομαι"
        },
        {
          "book_entry": "ὄλλυμι"
        },
        {
          "book_entry": "προάγω"
        },
        {
          "book_entry": "προκαταλαμβάνω, -ομαι"
        },
        {
          "book_entry": "συμβουλεύω"
        },
        {
          "book_entry": "συναγωνίζομαι"
        },
        {
          "book_entry": "συνέρχομαι"
        }
      ]
    },
    {
      "section": "Ὀνόματα",
      "words": [
        {
          "book_entry": "ἀγωνία, ἡ"
        },
        {
          "book_entry": "ἀθυμία, ἡ"
        },
        {
          "book_entry": "αἰτία, ἡ"
        },
        {
          "book_entry": "ἀνδριάς, ὁ"
        },
        {
          "book_entry": "ἀπάντησις, ἡ"
        },
        {
          "book_entry": "ἀπόστασις, ἡ"
        },
        {
          "book_entry": "δουλοσύνη, ἡ"
        },
        {
          "book_entry": "εἴδωλον, τό"
        },
        {
          "book_entry": "ἧττα, ἡ"
        },
        {
          "book_entry": "θρήνος, ὁ"
        },
        {
          "book_entry": "πάροδος, ἡ"
        },
        {
          "book_entry": "πεζομαχία, ἡ"
        },
        {
          "book_entry": "σπουδή, ἡ"
        },
        {
          "book_entry": "συναγώνισμα, τό"
        },
        {
          "book_entry": "σύνοδος, ἡ"
        },
        {
          "book_entry": "ὑπόθεσις, ἡ"
        }
      ]
    },
    {
      "section": "Κύρια ὀνόματα",
      "words": [
        {
          "book_entry": "Πλαταιαί, αἱ"
        }
      ]
    },
    {
      "section": "Ἀντωνυμίαι",
      "words": [
        {
          "book_entry": "οἷος, -α, -ον"
        }
      ]
    },
    {
      "section": "Ἐπίθετα",
      "words": [
        {
          "book_entry": "βοηθός, -όν"
        },
        {
          "book_entry": "ἐλάσσων, -ον"
        },
        {
          "book_entry": "εὔθετος, -ον"
        },
        {
          "book_entry": "ἱκανός, -ή, -όν"
        },
        {
          "book_entry": "λίθινος, -η, -ον"
        },
        {
          "book_entry": "ναυτικός, -ἡ, -όν"
        },
        {
          "book_entry": "ταπεινός, -ή, -όν"
        },
        {
          "book_entry": "τραγικός, -ή, -όν"
        },
        {
          "book_entry": "τριταῖος, -α, -ον"
        }
      ]
    },
    {
      "section": "Ἀριθμοί",
      "words": [
        {
          "book_entry": "δισχίλιοι, -αι, -α"
        },
        {
          "book_entry": "ἐνενήκοντα"
        },
        {
          "book_entry": "ἑξακισχίλιοι, -αι, -α"
        },
        {
          "book_entry": "τετρακόσιοι, -αι, -α"
        }
      ]
    },
    {
      "section": "Ἐπιρρήματα",
      "words": [
        {
          "book_entry": "ἀνδρειότατα"
        },
        {
          "book_entry": "ἐγγύς"
        }
      ]
    },
    {
      "section": "Μόρια",
      "words": [
        {
          "book_entry": "τοιγάρ"
        }
      ]
    }
  ]
}

=== obsgolem/LOGOSTools/json/Ch 1.json
{
  "chapter_name": "ΘΕΟΙ, ΑΝΘΡΩΠΟΙ ΚΑΙ ΘΗΡΙΑ",
  "word_list_page_number": 24,
  "exercise_page_range": [
    21,
    23
  ],
  "sections": [
    {
      "section": "Ῥήματα",
      "words": [
        {
          "book_entry": "ἐστίν | εἰσίν"
        }
      ]
    },
    {
      "section": "Ἀντωνυμίαι",
      "words": [
        {
          "book_entry": "τίς;"
        }
      ]
    },
    {
      "section": "Ὀνόματα",
      "words": [
        {
          "book_entry": "ἄνθρωπος, ὁ / ἡ"
        },
        {
          "book_entry": "ἄρθρον, τό"
        },
        {
          "book_entry": "ἀριθμός, ὁ"
        },
        {
          "book_entry": "βασίλεια, ἡ"
        },
        {
          "book_entry": "γραμματική, ἡ"
        },
        {
          "book_entry": "θεά, ἡ"
        },
        {
          "book_entry": "θεός, ὁ"
        },
        {
          "book_entry": "θηρίον, τό"
        },
        {
          "book_entry": "ἱέρεια, ἡ"
        },
        {
          "book_entry": "κεφάλαιον, τό"
        },
        {
          "book_entry": "μαθηματικός, ὁ"
        },
        {
          "book_entry": "μελέτημα, τό"
        },
        {
          "book_entry": "μουσικός, ὁ"
        },
        {
          "book_entry": "ποιήτρια, ἡ"
        },
        {
          "book_entry": "φιλόσοφος, ὁ"
        }
      ]
    },
    {
      "section": "Μόρια",
      "words": [
        {
          "book_entry": "δέ"
        },
        {
          "book_entry": "μέν"
        }
      ]
    },
    {
      "section": "Ἐπίθετα",
      "words": [
        {
          "book_entry": "Ἑλληνικός, -ή, -όν"
        },
        {
          "book_entry": "ἑνικός, -ἤ, -όν"
        },
        {
          "book_entry": "πληθυντικός, -ή, -όν"
        },
        {
          "book_entry": "Ρωμαϊκός, -ή, -όν"
        }
      ]
    },
    {
      "section": "Ἐπρρήματα",
      "words": [
        {
          "book_entry": "ἆρα;"
        },
        {
          "book_entry": "ναί"
        },
        {
          "book_entry": "οὐ | οὐκ | οὐχ"
        },
        {
          "book_entry": "οὐδαμῶς"
        }
      ]
    },
    {
      "section": "Ἄρθρον",
      "words": [
        {
          "book_entry": "ὁ, ἡ"
        }
      ]
    },
    {
      "section": "Σύνδεσμοι",
      "words": [
        {
          "book_entry": "ἀλλά"
        },
        {
          "book_entry": "καί"
        }
      ]
    },
    {
      "section": "Κύρια ὀνόματα",
      "words": [
        {
          "book_entry": "Ἀθηνᾶ, ἡ"
        },
        {
          "book_entry": "Ἀπόλλων, ὁ"
        },
        {
          "book_entry": "Ἄρης, ὁ"
        },
        {
          "book_entry": "Ἄρτεμις, ἡ"
        },
        {
          "book_entry": "Ἀστερίων, ὁ"
        },
        {
          "book_entry": "Ἀφροδίτη, ἡ"
        },
        {
          "book_entry": "Δημήτηρ, ἡ"
        },
        {
          "book_entry": "Διόνυσος, ὁ"
        },
        {
          "book_entry": "Διοτίμα, ἡ"
        },
        {
          "book_entry": "Ἑρμῆς, ὁ"
        },
        {
          "book_entry": "Ἥφαιστος, ὁ"
        },
        {
          "book_entry": "Ζεύς, ὁ"
        },
        {
          "book_entry": "Ἥρα, ἡ"
        },
        {
          "book_entry": "Κέρβερος, ὁ"
        },
        {
          "book_entry": "Κλεοπάτρα, ἡ"
        },
        {
          "book_entry": "Κόριννα, ἡ"
        },
        {
          "book_entry": "Μέδουσα, ἣ"
        },
        {
          "book_entry": "Ὀρφεύς, ὁ"
        },
        {
          "book_entry": "Περσεφόνη, ἡ"
        },
        {
          "book_entry": "Πήγασος, ὁ"
        },
        {
          "book_entry": "Πλάτων, ὁ"
        },
        {
          "book_entry": "Ποδάργη, ἡ"
        },
        {
          "book_entry": "Πολύφημος, ὁ"
        },
        {
          "book_entry": "Πυθαγόρας, ὁ"
        },
        {
          "book_entry": "Ὕδρα, ἡ"
        },
        {
          "book_entry": "Χείρων, ὁ"
        },
        {
          "book_entry": "Χίμαιρα, ἡ"
        }
      ]
    }
  ]
}
