=== obsgolem/LOGOSTools/schema.json
{
    "$schema": "https://json-schema.org/draft-07/schema",
    "$id": "https://raw.githubusercontent.com/obsgolem/LOGOSTools/main/schema.json",
    "title": "Chapter Vocabulary",
    "description": "The vocab list for a single chapter of ΛΟΓΟΣ",
    "type": "object",
    "properties": {
        "chapter_name": {
            "description": "The chapter's name",
            "type": "string"
        },
        "word_list_page_number": {
            "description": "The page number in the book for this list",
            "type": "number"
        },
        "exercise_page_range": {
            "description": "The page range for the exercises for this chapter",
            "type": "array",
            "minItems": 2,
            "maxItems": 2,
            "items": {
                "type": "number"
            }
        },
        "sections": {
            "type": "array",
            "items": {
                "description": "The collection of words under a section header in the book",
                "type": "object",
                "properties": {
                    "section": {
                        "description": "The name of the section in the book",
                        "type": "string"
                    },
                    "words": {
                        "type": "array",
                        "items": {
                            "description": "The data for a single vocab entry",
                            "type": "object",
                            "properties": {
                                "book_entry": {
                                    "description": "The raw text in the book",
                                    "type": "string"
                                },
                                "first_occurrence": {
                                    "description": "The line and word number (1 indexed) of the first occurrence of the word in the book.",
                                    "type": "array",
                                    "minItems": 1,
                                    "maxItems": 2,
                                    "items": {
                                        "type": "number"
                                    }
                                },
                                "macronized": {
                                    "description": "The entry with any ambiguous long vowels macronized.",
                                    "type": "string"
                                },
                                "gloss": {
                                    "description": "A short definition in english for the word.",
                                    "type": "string"
                                }
                            },
                            "additionalProperties": false,
                            "required": [
                                "book_entry"
                            ]
                        }
                    }
                },
                "additionalProperties": false,
                "required": [
                    "section",
                    "words"
                ]
            }
        }
    }
}

=== obsgolem/LOGOSTools/json/Ch 11.json
{
  "chapter_name": "Ω ΖΕΥ! Ω ΗΡΑ!",
  "word_list_page_number": 112,
  "exercise_page_range": [
    107,
    111
  ],
  "sections": [
    {
      "section": "Ῥήματα",
      "words": [
        {
          "book_entry": "ἀνατέλλω",
          "first_occurrence": [
            1,
            3
          ]
        },
        {
          "book_entry": "ἀνοίγω",
          "first_occurrence": [
            3,
            4
          ]
        },
        {
          "book_entry": "ἀπαλλάσσω",
          "first_occurrence": [
            12,
            6
          ]
        },
        {
          "book_entry": "ἀποκρίνομαι",
          "first_occurrence": [
            18,
            4
          ]
        },
        {
          "book_entry": "ἀφυπνίζω",
          "first_occurrence": [
            25,
            6
          ]
        },
        {
          "book_entry": "ἐγείρω, -ομαι",
          "first_occurrence": [
            2,
            5
          ]
        },
        {
          "book_entry": "ἐκβαίνω",
          "first_occurrence": [
            4,
            4
          ]
        },
        {
          "book_entry": "ἐνδύω, -ομαι",
          "first_occurrence": [
            4,
            1
          ]
        },
        {
          "book_entry": "ἐρωτάω",
          "first_occurrence": [
            39,
            5
          ]
        },
        {
          "book_entry": "καταβαίνω",
          "first_occurrence": [
            5,
            1
          ]
        },
        {
          "book_entry": "νίζω",
          "first_occurrence": [
            6,
            4
          ]
        },
        {
          "book_entry": "προσεύχομαι",
          "first_occurrence": [
            8,
            4
          ]
        },
        {
          "book_entry": "στενάζω",
          "first_occurrence": [
            20,
            4
          ]
        },
        {
          "book_entry": "τιμάω",
          "first_occurrence": [
            11,
            6
          ]
        },
        {
          "book_entry": "φέρω",
          "first_occurrence": [
            23,
            2
          ]
        }
      ]
    },
    {
      "section": "Φράσεις",
      "words": [
        {
          "book_entry": "ἐν ᾧ",
          "first_occurrence": [
            30,
            6
          ]
        },
        {
          "book_entry": "μὰ τόν Δία"
        }
      ]
    },
    {
      "section": "Ὀνόματα",
      "words": [
        {
          "book_entry": "ἄρτος, ὁ",
          "first_occurrence": [
            48,
            9
          ]
        },
        {
          "book_entry": "γάλα, τό",
          "first_occurrence": [
            61,
            7
          ]
        },
        {
          "book_entry": "κάνθαρος, ὁ",
          "first_occurrence": [
            66,
            2
          ]
        },
        {
          "book_entry": "κύλιξ, ἡ",
          "first_occurrence": [
            72,
            1
          ]
        },
        {
          "book_entry": "λεκάκιον, τό",
          "first_occurrence": [
            75,
            7
          ]
        },
        {
          "book_entry": "μέλι, τό",
          "first_occurrence": [
            52,
            1
          ]
        },
        {
          "book_entry": "ὄρθρος, ὁ",
          "first_occurrence": [
            1,
            5
          ]
        },
        {
          "book_entry": "πρόσωπον, τό",
          "first_occurrence": [
            6,
            3
          ]
        },
        {
          "book_entry": "συμφορά, ἡ",
          "first_occurrence": [
            11,
            2
          ]
        },
        {
          "book_entry": "τυρός, ὁ",
          "first_occurrence": [
            38,
            7
          ]
        },
        {
          "book_entry": "ὑδρία, ἡ",
          "first_occurrence": [
            62,
            2
          ]
        },
        {
          "book_entry": "χιτών, ὁ",
          "first_occurrence": [
            3,
            7
          ]
        }
      ]
    },
    {
      "section": "Ἐπίθετα",
      "words": [
        {
          "book_entry": "μόνος, -η, -ον",
          "first_occurrence": [
            27,
            9
          ]
        },
        {
          "book_entry": "πονηρός, -ά, -όν",
          "first_occurrence": [
            21,
            9
          ]
        },
        {
          "book_entry": "_προστακτικός, -ή, -όν_"
        },
        {
          "book_entry": "σοφός, -ή, -όν",
          "first_occurrence": [
            9,
            6
          ]
        },
        {
          "book_entry": "τάλας, τάλαινα, τάλαν",
          "first_occurrence": [
            21,
            1
          ]
        }
      ]
    },
    {
      "section": "Προθέσεις",
      "words": [
        {
          "book_entry": "διά (διὰ τί;)"
        },
        {
          "book_entry": "ἐπί + δοτ."
        },
        {
          "book_entry": "κατά + γεν."
        },
        {
          "book_entry": "μετά (μετὰ ταῦτα)"
        },
        {
          "book_entry": "πρός + αἷτ."
        },
        {
          "book_entry": "σύν"
        },
        {
          "book_entry": "ὑπό + δοτ."
        }
      ]
    },
    {
      "section": "Ἀντωνυμίαι",
      "words": [
        {
          "book_entry": "ἐγώ",
          "first_occurrence": [
            11,
            4
          ]
        },
        {
          "book_entry": "οὐδείς, οὐδεμία, οὐδέν",
          "first_occurrence": [
            47,
            1
          ]
        },
        {
          "book_entry": "σύ",
          "first_occurrence": [
            9,
            8
          ]
        }
      ]
    },
    {
      "section": "Μόρια",
      "words": [
        {
          "book_entry": "γε",
          "first_occurrence": [
            74,
            3
          ]
        },
        {
          "book_entry": "δή",
          "first_occurrence": [
            47,
            8
          ]
        }
      ]
    },
    {
      "section": "Ἐπιρρήματα",
      "words": [
        {
          "book_entry": "μάλιστα",
          "first_occurrence": [
            74,
            2
          ]
        },
        {
          "book_entry": "οὐκέτι",
          "first_occurrence": [
            32,
            7
          ]
        },
        {
          "book_entry": "πάλιν",
          "first_occurrence": [
            53,
            4
          ]
        },
        {
          "book_entry": "πόθεν;",
          "first_occurrence": [
            42,
            4
          ]
        }
      ]
    }
  ]
}

=== obsgolem/LOGOSTools/json/Ch 17.json
{
  "chapter_name": "ΤΑ ΜΕΡΗ ΤΟΥ ΣΩΜΑΤΟΣ",
  "word_list_page_number": 180,
  "exercise_page_range": [
    176,
    179
  ],
  "sections": [
    {
      "section": "Ῥήματα",
      "words": [
        {
          "book_entry": "ἀλλάσσω"
        },
        {
          "book_entry": "ἀπάγω",
          "first_occurrence": [
            140,
            4
          ]
        },
        {
          "book_entry": "ἀπαρνέομαι",
          "first_occurrence": [
            120,
            5
          ]
        },
        {
          "book_entry": "ἅπτω, -ομαι",
          "first_occurrence": [
            110,
            1
          ]
        },
        {
          "book_entry": "ἁρπάζω, -ομαι",
          "first_occurrence": [
            139,
            2
          ]
        },
        {
          "book_entry": "βιάζω, -ομαι",
          "first_occurrence": [
            126,
            6
          ]
        },
        {
          "book_entry": "διώκω. -ομαι",
          "first_occurrence": [
            93,
            4
          ]
        },
        {
          "book_entry": "κατοικέω",
          "first_occurrence": [
            104,
            2
          ]
        },
        {
          "book_entry": "κινέω, -έομαι",
          "first_occurrence": [
            9,
            1
          ]
        },
        {
          "book_entry": "μεταβάλλω, -ομαι",
          "first_occurrence": [
            98,
            7
          ]
        },
        {
          "book_entry": "ὁμιλέω",
          "first_occurrence": [
            136,
            4
          ]
        },
        {
          "book_entry": "ὀσφραίνομαι",
          "first_occurrence": [
            19,
            8
          ]
        },
        {
          "book_entry": "ὑβρίζω",
          "first_occurrence": [
            117,
            4
          ]
        }
      ]
    },
    {
      "section": "Ἐπίθετα",
      "words": [
        {
          "book_entry": "ἀνθρώπινος, -η, -ον",
          "first_occurrence": [
            2,
            8
          ]
        },
        {
          "book_entry": "γυμνός, -ή, -όν",
          "first_occurrence": [
            131,
            2
          ]
        },
        {
          "book_entry": "ἔμπειρος, -ον",
          "first_occurrence": [
            103,
            1
          ]
        },
        {
          "book_entry": "ζῳοκέφαλος, -ον",
          "first_occurrence": [
            71,
            3
          ]
        },
        {
          "book_entry": "ἱερός, -ά, -όν",
          "first_occurrence": [
            94,
            6
          ]
        },
        {
          "book_entry": "_παθητικός, ή, -όν_"
        },
        {
          "book_entry": "πᾶς, πᾶσα, πᾶν",
          "first_occurrence": [
            7,
            4
          ]
        },
        {
          "book_entry": "πτερωτός, -ή, -όν",
          "first_occurrence": [
            60,
            5
          ]
        },
        {
          "book_entry": "τεράστιος, -ον"
        },
        {
          "book_entry": "χωλός, -ή, -όν",
          "first_occurrence": [
            56,
            3
          ]
        }
      ]
    },
    {
      "section": "Ἀριθμοί",
      "words": [
        {
          "book_entry": "εἰκοσιδύο",
          "first_occurrence": [
            106,
            7
          ]
        },
        {
          "book_entry": "πεντήκοντα",
          "first_occurrence": [
            79,
            1
          ]
        }
      ]
    },
    {
      "section": "Ὀνόματα",
      "words": [
        {
          "book_entry": "αἴξ, ἡ",
          "first_occurrence": [
            64,
            2
          ]
        },
        {
          "book_entry": "ἀρχή, ἡ",
          "first_occurrence": [
            2,
            2
          ]
        },
        {
          "book_entry": "βοῦς, ἡ / ὸ"
        },
        {
          "book_entry": "γίγας, ὁ",
          "first_occurrence": [
            75,
            5
          ]
        },
        {
          "book_entry": "δάκτυλος, ὁ"
        },
        {
          "book_entry": "δάφνη, ἡ",
          "first_occurrence": [
            94,
            3
          ]
        },
        {
          "book_entry": "ζωή, ἡ",
          "first_occurrence": [
            3,
            1
          ]
        },
        {
          "book_entry": "ἡγεμών, ὁ",
          "first_occurrence": [
            53,
            3
          ]
        },
        {
          "book_entry": "θάνατος, ὁ"
        },
        {
          "book_entry": "κέρας, τό",
          "first_occurrence": [
            73,
            1
          ]
        },
        {
          "book_entry": "κίνησις, ἡ",
          "first_occurrence": [
            9,
            8
          ]
        },
        {
          "book_entry": "κρᾶσις, ἡ",
          "first_occurrence": [
            59,
            5
          ]
        },
        {
          "book_entry": "μέρος, τό"
        },
        {
          "book_entry": "μεταβολή, ἡ",
          "first_occurrence": [
            96,
            5
          ]
        },
        {
          "book_entry": "μορφή, ἡ",
          "first_occurrence": [
            10,
            4
          ]
        },
        {
          "book_entry": "ὀδούς, ὁ",
          "first_occurrence": [
            21,
            6
          ]
        },
        {
          "book_entry": "οὐρά, ἡ",
          "first_occurrence": [
            44,
            6
          ]
        },
        {
          "book_entry": "οὖς, τό"
        },
        {
          "book_entry": "πτερόν, τό",
          "first_occurrence": [
            37,
            6
          ]
        },
        {
          "book_entry": "ῥάβδος, ἡ",
          "first_occurrence": [
            109,
            7
          ]
        },
        {
          "book_entry": "ῥῖς, ἡ",
          "first_occurrence": [
            18,
            7
          ]
        },
        {
          "book_entry": "στόμα, τό",
          "first_occurrence": [
            17,
            3
          ]
        },
        {
          "book_entry": "_σύνταξις, ἡ_"
        },
        {
          "book_entry": "τέλος, τό",
          "first_occurrence": [
            2,
            5
          ]
        },
        {
          "book_entry": "ὕβρις, ἡ",
          "first_occurrence": [
            124,
            2
          ]
        },
        {
          "book_entry": "ὑφάντρια, ἡ",
          "first_occurrence": [
            123,
            4
          ]
        },
        {
          "book_entry": "φάρμακον, τό",
          "first_occurrence": [
            113,
            1
          ]
        },
        {
          "book_entry": "φύλαξ, ὁ",
          "first_occurrence": [
            84,
            6
          ]
        },
        {
          "book_entry": "φύσις, ἡ",
          "first_occurrence": [
            4,
            7
          ]
        },
        {
          "book_entry": "φυτόν, τό",
          "first_occurrence": [
            94,
            7
          ]
        },
        {
          "book_entry": "χείρ, ἡ",
          "first_occurrence": [
            13,
            4
          ]
        },
        {
          "book_entry": "ψυχή, ἡ",
          "first_occurrence": [
            3,
            7
          ]
        }
      ]
    },
    {
      "section": "Κυρια ὀνόματα",
      "words": [
        {
          "book_entry": "Ἐλευσίς, ἡ"
        },
        {
          "book_entry": "Αἰαία, ἡ"
        },
        {
          "book_entry": "Ἀκταίων, ὁ"
        },
        {
          "book_entry": "Ἀράχνη, ἡ"
        },
        {
          "book_entry": "Γανυμήδης, ὁ"
        },
        {
          "book_entry": "Γλαῦκος, ὁ"
        },
        {
          "book_entry": "Γοργών, ἡ"
        },
        {
          "book_entry": "Εὐρύλοχος, ὁ"
        },
        {
          "book_entry": "Ἥλιος, ὁ"
        },
        {
          "book_entry": "Κίρκη, ἡ"
        },
        {
          "book_entry": "Λήδα, ἡ"
        },
        {
          "book_entry": "Μετίοχος, ὁ"
        },
        {
          "book_entry": "Πέρση, ἡ"
        },
        {
          "book_entry": "Σωκράτης, ὁ"
        },
        {
          "book_entry": "Τηλέμαχος, ὁ"
        }
      ]
    },
    {
      "section": "Ἐπιρρήματα",
      "words": [
        {
          "book_entry": "ἔκτοτε",
          "first_occurrence": [
            94,
            1
          ]
        },
        {
          "book_entry": "ἐνίοτε",
          "first_occurrence": [
            89,
            1
          ]
        },
        {
          "book_entry": "πολλάκις",
          "first_occurrence": [
            136,
            5
          ]
        }
      ]
    },
    {
      "section": "Ἀντωνυμίαι",
      "words": [
        {
          "book_entry": "ἕκαστος, -η, -ον",
          "first_occurrence": [
            107,
            9
          ]
        }
      ]
    },
    {
      "section": "Προθέσεις",
      "words": [
        {
          "book_entry": "πλήν",
          "first_occurrence": [
            54,
            6
          ]
        }
      ]
    }
  ]
}

=== obsgolem/LOGOSTools/json/Ch 14.json
{
  "chapter_name": "Ο ΚΥΚΛΩΨ",
  "word_list_page_number": 145,
  "exercise_page_range": [
    141,
    144
  ],
  "sections": [
    {
      "section": "Ῥήματα",
      "words": [
        {
          "book_entry": "ἀδικέω"
        },
        {
          "book_entry": "ἀναβοάω"
        },
        {
          "book_entry": "ἀνακαίω"
        },
        {
          "book_entry": "ἀπέρχομαι"
        },
        {
          "book_entry": "ἀποβαίνω"
        },
        {
          "book_entry": "ἀποξύνω"
        },
        {
          "book_entry": "ἀποπλέω"
        },
        {
          "book_entry": "βάλλω"
        },
        {
          "book_entry": "βοάω"
        },
        {
          "book_entry": "βυθίζω"
        },
        {
          "book_entry": "εἰσβαίνω"
        },
        {
          "book_entry": "εἰσελαύνω"
        },
        {
          "book_entry": "ἐκλύω"
        },
        {
          "book_entry": "ἐξέρχομαι"
        },
        {
          "book_entry": "ἐπανέρχομαι"
        },
        {
          "book_entry": "ἐπιζητέω"
        },
        {
          "book_entry": "καίω"
        },
        {
          "book_entry": "καταντάω"
        },
        {
          "book_entry": "κεραννύω"
        },
        {
          "book_entry": "κοιμάομαι"
        },
        {
          "book_entry": "κρύπτω, -ομαι"
        },
        {
          "book_entry": "μανθάνω"
        },
        {
          "book_entry": "μεθύω"
        },
        {
          "book_entry": "μηνίω"
        },
        {
          "book_entry": "νομίζω"
        },
        {
          "book_entry": "παραγίγνομαι"
        },
        {
          "book_entry": "πάσχω"
        },
        {
          "book_entry": "περιρρέω"
        },
        {
          "book_entry": "πλανάω, -άομαι"
        },
        {
          "book_entry": "προσπελάζω"
        },
        {
          "book_entry": "προστίθημι"
        },
        {
          "book_entry": "σώζω, -ομαι"
        },
        {
          "book_entry": "τρίβω"
        },
        {
          "book_entry": "τυφλόω"
        },
        {
          "book_entry": "φοβέω, -έομαι"
        }
      ]
    },
    {
      "section": "Ὀνόματα",
      "words": [
        {
          "book_entry": "ἀσκός, ὁ"
        },
        {
          "book_entry": "βασιλεύς, ὁ"
        },
        {
          "book_entry": "βοή, ἡ"
        },
        {
          "book_entry": "γαστήρ, ἡ"
        },
        {
          "book_entry": "δόλος, ὁ"
        },
        {
          "book_entry": "ἐπεισόδιον, τό"
        },
        {
          "book_entry": "ἑταῖρος, ὁ"
        },
        {
          "book_entry": "κρατήρ, ὁ"
        },
        {
          "book_entry": "κριός, ὁ"
        },
        {
          "book_entry": "λίθος, ὁ"
        },
        {
          "book_entry": "μέτωπον, τό"
        },
        {
          "book_entry": "ναῦς, ἡ"
        },
        {
          "book_entry": "ὀφθαλμός, ὁ"
        },
        {
          "book_entry": "ποίμνιον, τό"
        },
        {
          "book_entry": "ῥόπαλον, τό"
        },
        {
          "book_entry": "στόμαχος, ὁ"
        }
      ]
    },
    {
      "section": "Ἐπίθετα",
      "words": [
        {
          "book_entry": "ἄκρατος, -ον"
        },
        {
          "book_entry": "ἀνδροφάγος, -ον"
        },
        {
          "book_entry": "γλυκύς, -εἴα, τύ"
        },
        {
          "book_entry": "διάπυρος, -ον"
        },
        {
          "book_entry": "ἔνδοξος, -ον"
        },
        {
          "book_entry": "ἡδύποτος, -ον"
        },
        {
          "book_entry": "λευκός, -ή, τόν"
        },
        {
          "book_entry": "λυπηρός, -ά, -όν"
        },
        {
          "book_entry": "λωτοφόγος, -ον"
        },
        {
          "book_entry": "οὐρητικός, -ή, -όν"
        },
        {
          "book_entry": "πεπτικός, -ή, -όν"
        },
        {
          "book_entry": "πολύτροπος, -ον"
        },
        {
          "book_entry": "συνήθης, -ες"
        },
        {
          "book_entry": "_σύνθετος, -ον_"
        },
        {
          "book_entry": "τρόφιμος, -η, -ον"
        },
        {
          "book_entry": "τυφλός, -ή, -όν"
        },
        {
          "book_entry": "ὑπέρμεγας, -άλη, -αν"
        },
        {
          "book_entry": "ὑπερμεγέθης, -ες"
        },
        {
          "book_entry": "ὑστεραίος, -α, τον"
        }
      ]
    },
    {
      "section": "Κύρια ὀνόματα",
      "words": [
        {
          "book_entry": "Θοώσα, ἡ"
        },
        {
          "book_entry": "Ὀδύσσεια, ἡ"
        },
        {
          "book_entry": "Ἴλιον, τό"
        },
        {
          "book_entry": "Λαέρτης, ὁ"
        },
        {
          "book_entry": "Ὀδυσσεύς, ὁ"
        }
      ]
    },
    {
      "section": "Ἐπιρρήματα",
      "words": [
        {
          "book_entry": "οὕτω(ς)"
        },
        {
          "book_entry": "πέριξ"
        },
        {
          "book_entry": "πλησίον"
        },
        {
          "book_entry": "ταχέως"
        }
      ]
    },
    {
      "section": "Φράσεις",
      "words": [
        {
          "book_entry": "ἐκ τούτου"
        },
        {
          "book_entry": "τῇ ὑστεραίᾳ"
        }
      ]
    },
    {
      "section": "Ἀντωνυμίαι",
      "words": [
        {
          "book_entry": "οὔτις"
        }
      ]
    },
    {
      "section": "Ἀριθμοί",
      "words": [
        {
          "book_entry": "δώδεκα"
        }
      ]
    },
    {
      "section": "Προθέσεις",
      "words": [
        {
          "book_entry": "ἀπό + γεν."
        },
        {
          "book_entry": "εἰς"
        },
        {
          "book_entry": "ἐπί + γεν."
        },
        {
          "book_entry": "μετά + γεν."
        },
        {
          "book_entry": "ὑπό + γεν. / αἰτ."
        }
      ]
    }
  ]
}

=== obsgolem/LOGOSTools/json/Ch 2.json
{
  "chapter_name": "ΑΝΔΡΕΣ ΚΑΙ ΓΥΝΑΙΚΕΣ",
  "word_list_page_number": 32,
  "exercise_page_range": [
    28,
    31
  ],
  "sections": [
    {
      "section": "Ὀνόματα",
      "words": [
        {
          "book_entry": "ἀνήρ, ὁ",
          "first_occurrence": [
            1,
            3
          ]
        },
        {
          "book_entry": "_γένος, τό_"
        },
        {
          "book_entry": "γυνή, ἡ",
          "first_occurrence": [
            7,
            7
          ]
        },
        {
          "book_entry": "κόρη, ἡ",
          "first_occurrence": [
            26,
            2
          ]
        },
        {
          "book_entry": "νεανίας, ὁ",
          "first_occurrence": [
            25,
            5
          ]
        },
        {
          "book_entry": "παῖς, ὁ/ἡ",
          "first_occurrence": [
            18,
            6
          ]
        },
        {
          "book_entry": "παιδίον, τό",
          "first_occurrence": [
            20,
            4
          ]
        }
      ]
    },
    {
      "section": "Ἐπίθετα",
      "words": [
        {
          "book_entry": "ἀθάνατος, -ον",
          "first_occurrence": [
            43,
            6
          ]
        },
        {
          "book_entry": "_ἀρσενικός, -ή, -όν_"
        },
        {
          "book_entry": "_θηλυκός, -ή, -όν_"
        },
        {
          "book_entry": "θνητός, -ή, -όν",
          "first_occurrence": [
            43,
            3
          ]
        },
        {
          "book_entry": "κακός, -ή, -ον",
          "first_occurrence": [
            32,
            2
          ]
        },
        {
          "book_entry": "καλός, -ή, -όν",
          "first_occurrence": [
            31,
            5
          ]
        },
        {
          "book_entry": "_οὐδέτερος, -τέρα, -τερον_"
        }
      ]
    },
    {
      "section": "Ἄρθρον",
      "words": [
        {
          "book_entry": "ὁ, ἡ, τό | οἱ, αἱ, τά",
          "first_occurrence": [
            15,
            6
          ]
        }
      ]
    },
    {
      "section": "Ἀριθμοί",
      "words": [
        {
          "book_entry": "δύο",
          "first_occurrence": [
            3,
            2
          ]
        },
        {
          "book_entry": "τρεῖς",
          "first_occurrence": [
            6,
            3
          ]
        }
      ]
    },
    {
      "section": "Σύνδεσμοι",
      "words": [
        {
          "book_entry": "γάρ",
          "first_occurrence": [
            25,
            3
          ]
        },
        {
          "book_entry": "ἤ",
          "first_occurrence": [
            66,
            5
          ]
        },
        {
          "book_entry": "οὔτε ... οὔτε",
          "first_occurrence": [
            24,
            3
          ]
        }
      ]
    },
    {
      "section": "Μόρια",
      "words": [
        {
          "book_entry": "οὖν",
          "first_occurrence": [
            13,
            3
          ]
        }
      ]
    },
    {
      "section": "Κύρα ὀνόματα",
      "words": [
        {
          "book_entry": "Ἀπολλόδωρος, ὁ"
        },
        {
          "book_entry": "Ἀπολλώνιος, ὁ"
        },
        {
          "book_entry": "Ἑλένη, ἡ"
        },
        {
          "book_entry": "Ἠλέκτρα, ἡ"
        },
        {
          "book_entry": "Καλλίμαχος, ὁ"
        },
        {
          "book_entry": "Καλλιρρόη, ἡ"
        },
        {
          "book_entry": "Κασσάνδρα, ἡ",
          "first_occurrence": [
            22,
            3
          ]
        },
        {
          "book_entry": "Πάτροκλος, ὁ",
          "first_occurrence": [
            22,
            6
          ]
        },
        {
          "book_entry": "Ὑπατία, ἡ",
          "first_occurrence": [
            17,
            4
          ]
        },
        {
          "book_entry": "Φίλιππος, ὁ",
          "first_occurrence": [
            4,
            1
          ]
        }
      ]
    }
  ]
}
